### PR TITLE
Add --column argument

### LINKED ISSUE #37: Add --column argument.
I'm not sure how much hassle it would be to add an --column argument to not only print matching line number but also matching column while not affecting performance too much.  Since it would be optional I guess that the eventual negative performance would only apply to when this argument is in use. 

I'm writing this because wanting to have pt working well with a emacs package called ag.el.
https://github.com/Wilfred/ag.el/issues/46

### PR DESCRIPTION
**Pull request by thomasf**
fixes #37  which I just saw also has another open pull request in #73

### CODE REVIEW

**Comment by thomasf** [comment]
I have improved the design a couple of iterations and A/B compared it using bash time'd bash-scripts and lightly looked at pprof results..

My implementation only calculates column value if it's requested using --column..
I tested everything on about 1.5gb data residing on a  ram disk to avoid random fluctuations caused by  disk io. The difference for queries with lots of results were quite big, somewhere along the lines of 4 seconds vs 6 seconds..  This  adds a tiny bit of complexity to the code, and I chose to propagate the --column option through the Match type since that seemed like what was going on earlier as well.  I'm still not sure about if it's worth it generally but for searches in very large data sets on very fast io it probably makes sense. 

Let me know if some changes should be made.

**Comment by thomasf** [comment]
should probably save the match regions in full for use in both match highlight and column number

**Comment by vermiculus** [comment]
:+1: would be super helpful to have this -- some tools (eg emacs) depend on file-line-column to provide a reference point to jump to.

**Comment by thomasf** [comment]
@vermiculus yeah  emacs ant pt.el is my use case for this patch, see https://github.com/Wilfred/ag.el/issues/46 ..  I do think the design is flawed though as I wrote in my last comment. I am hoping to get a comment/direction from @monochromegane because I do not want to spend more time implementing something that won't be merged.

**Comment by monochromegane** [comment]
Thanks for your PR, and I am sorry for the late response.
I tried your PR and https://github.com/monochromegane/the_platinum_searcher/pull/73.
Both PR is nice, but #73 has a problem as you say, so this time I will merge this PR.

**Comment by thomasf** [comment]
thanks!

**Pull request merged**
