### PR TITLE
V2

### PR DESCRIPTION
**Pull request by monochromegane**
# v2

This is a v2 release note.

## The platinum searcher should be fast.

Now pt has many options and features, but got slow. So, I have re-writed in this v2 branch.

- Refactor.
- Enable parallel option always.
- Reduce calling syscall.Read.
- Reduce memory alloc.
- Reduce unncessary tranfer encoding.
- Tuned channel number.
- Use simple index tree for fast matching gitignore, and separate to [other package](https://github.com/monochromegane/go-gitignore).
- Stop use print channel.
- Remove some unncessary options, and change some default behavior.
- And fix some bugs.

## Benchmark

**v2.0.0 searches code about 2-5x faster than v1.7.9 :star2:**

Execution time (sec)

| -        | v1.7.9  | v2.0.0 |
| -------- | -------:| ------:|
| cached   | 5.203   | 0.977  |
| no cache | 11.524  | 4.643  |

spec: MacBook Pro (OS X 10.11.1 / CPU: 2.5GHz, Memory: 8GB)

command: `time pt EXPORT_SYMBOL_GPL ~/src/github.com/torvalds/linux > /dev/null`

## Changes

- `vcs-ignore` option's default value is now set only `.gitignore`.
- `noptignore` option is removed because `~/.ptignore` is not reference by default. If you use this, you can specify new `ptignore` option.
- `noglobal-gitignore` option is removed because `~/.gitignore` is not reference by default. If you use this, you can specify new `global-gitignore` option.
- `parallel` option is removed because pt use this option always.
- `g (FilesWithRegexp)` option is removed because nobody use maybe.
- `stats` option is removed because nobody use maybe.
- `Search Stream` (e.g. `cat hoge.txt | pt pattern`) is removed because this feature can't detect encoding.

## Implementation TODO

Completed.

### Features

- [x] Refactor and tune up basic features (find, grep and print)
- [x] detection encoding
- [x] ptconfig.toml
- [x] gitignore

### Options

Application Options

- [x] Version

Search Options

- [x] Hidden
- [x] Depth
- [x] Regexp
- [x] WordRegexp
- [x] SkipVcsIgnore
- [x] Follow
- [x] IgnoreCase
- [x] SmartCase
- [x] Ignore
- [x] VcsIgnore
- [x] PtIgnore
- [x] GlobalGitIgnore
- [x] FileSearchRegexp

Output Options

- [x] Color
- [x] NoColor
- [x] NoGroup
- [x] FilesWithMatches
- [x] Count
- [x] After
- [x] Before
- [x] Context
- [x] Column
- [x] OutputEncode

### CODE REVIEW

**Comment by jsfaint** [comment]
`pt` is a good tools, thank you!

But it's a pity that `-g` option was removed in v2, and same with "Search Stream" function.
Without these functions, pt can't be a fully replacement to ag/ack/grep.
For example, I use pt with ctrlp in Vim to list the file.

I know `find` command is more quick in *nix, but in windows, pt is a good choice. Because I use same vim config in the different platform.

Thanks again.

**Comment by monochromegane** [comment]
Thank you for using pt !
I will re-implement these feature this month.
Please wait new version :smile:

**Comment by dkotvan** [comment]
I miss the -g feature too. :+1: 

Thanks for this tool. It's great.

**Comment by mmaz** [comment]
I also use the `-g` feature along with https://github.com/peco/peco to quickly open files in emacs. This bash function replicates [the Github File Browser `t` shortcut](https://help.github.com/articles/using-keyboard-shortcuts/#source-code-browsing) for instance:

```
function t() {
    local FILE
    FILE=$(ag -g "" | peco)
    if [ -n "$FILE" ]; then
        emacsclient -cq $FILE &
    fi
}
```

**Comment by jsfaint** [comment]
@monochromegane It's good to hear that,  Thank you :)

**Comment by monochromegane** [comment]
Hi, @jsfaint @dkotvan @mmaz .
I have released v2.0.1 now.
I implemented lost features (`Seach Stream` and `g option`) again.
Please try it :smile: 
Thank you for using pt :beers:

**Pull request merged**
