### PR TITLE
Add --column argument

### PR DESCRIPTION
**Pull request by lvela**
Implements #37. 

```
$  pt --column Test
grep_test.go:
24:6:func TestGrep(t *testing.T) {
45:6:func TestGrepWithStream(t *testing.T) {

pattern_test.go:
12:6:func TestIgnoreCaseWithSmartCase(t *testing.T) {

ignore_test.go:
16:6:func TestGenericIgnoreMatch(t *testing.T) {
34:6:func TestGitIgnoreMatch(t *testing.T) {
67:6:func TestGitIgnoreMatchOnSubDirectory(t *testing.T) {
...
```

```
$ pt --nocolor --nogroup --column Test
grep_test.go:24:6:func TestGrep(t *testing.T) {
grep_test.go:45:6:func TestGrepWithStream(t *testing.T) {
file_test.go:23:6:func TestIdentifyType(t *testing.T) {
match_test.go:49:6:func TestMatch(t *testing.T) {
match_test.go:76:6:func TestMatchWhenContextAndMatchDuplicate(t *testing.T) {
find_test.go:28:6:func TestFind(t *testing.T) {
...
```
Then I could add this for Ack.vim plugin
```
let g:ackprg = 'pt --nogroup --nocolor --column'
```

### CODE REVIEW

**Comment by thomasf** [comment]
Oops, i just impemented this as well. 
Why did you add Col to Line instead of Match?

**Comment by lvela** [comment]
It seemed like a logical place to me at the time. I'm not really sure there is any advantage there over Match.

**Comment by thomasf** [comment]
Your version seems to be a little bit faster, I'm trying to figure out why.
I probably did a bad thing (non backed up/premature optimization) because I thought that It would be better to only find the column value only when it is going to be printed.  

After reading both solutions a few times this a couple of times again I saw that you have missed to check using :

image

**Comment by thomasf** [comment]
While rereading both solutions a copule of times I saw a bug in your version: 

image

**Comment by thomasf** [comment]
Had another look now,. the reason for the small but rather constant execution time difference was that I added ansi color to the column marker as well as line number.

**Comment by lvela** [comment]
Good catch. It's because of the rudimentary way I set the column at https://github.com/lvela/the_platinum_searcher/blob/master/match.go#L88 

I wasn't really planning on working on this more so maybe your version could be merged in and you could incorporate some of my code if you find it useful.

**Comment by vermiculus** [comment]
:+1: would be super helpful to have this -- some tools (eg emacs) depend on file-line-column to provide a reference point to jump to.

(Related to #79 -- no idea which should be merged.)

**Comment by monochromegane** [comment]
Thanks for your PR, and I am sorry for the late response.
This time I merged #79, as I commented https://github.com/monochromegane/the_platinum_searcher/pull/79#issuecomment-104967090 .

**Pull request closed without merging**
