### PR TITLE
Comply with semantic import versioning

### PR DESCRIPTION
**Pull request by Loyalsoldier**

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
For Go v1.15.6 in Homebrew https://github.com/Homebrew/homebrew-core/pull/66355

**Comment by carlocab** [comment]
Thanks, @Loyalsoldier.

If this PR is merged, it would also be helpful for Homebrew if you cut a new release that includes this PR. At the moment CI failures associated with formulae that still depend on `godep` is holding back the `go` version bump.

**Comment by shigemk2** [comment]
How about wercker.yml? 
the_platinum_searcher uses wercker as CI tool.
We have to delete godep from wercker.yml https://github.com/monochromegane/the_platinum_searcher/blob/master/wercker.yml#L5-L18.

**Comment by carlocab** [comment]
If you make that change, please squash your commits so I only need one commit hash for the Homebrew patch.

**Comment by shigemk2** [comment]
Well, I do not have to fix wercker.yml right away because wercker uploads artifacts.

**Pull request closed without merging**
